export const PATHS = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  pay: "/pay",
  inventory: "/inventory",
  external: "/external",
  externalnew: "/externalnew",
  externalid: "/external/:id",
  team: "/team",
  clients: "/clients",
  clientDetail: "/clients/:id",
  evaluations: "/evaluations",
  evaluationNew: "/evaluations/new", 
  evaluationDetail: "/evaluations/:id", 
  external: "/external",
  externalnew: "/external/new",
  externalid: "/external/:id",
};